(cl:in-package #:common-lisp-user)

(defpackage #:hirundine-graph
  (:use #:common-lisp)
  (:export
   #:instruction
   #:origin
   #:inputs
   #:outputs
   #:predecessors
   #:successors
   #:map-instructions-arbitrary-order
   #:initialize-predecessors-and-data
   #:check-hir
   #:parse-arguments-instruction
   #:lambda-list
   #:static-environment-register
   #:dynamic-environment-register
   #:nop-instruction
   #:make-cell-instruction
   #:read-cell-instruction
   #:write-cell-instruction
   #:set-static-environment-instruction
   #:read-static-environment-instruction
   #:if-instruction
   #:block-instruction
   #:tagbody-instruction
   #:return-from-instruction
   #:go-instruction
   #:receive-instruction
   #:funcall-instruction
   #:multiple-value-call-instruction
   #:return-instruction
   #:assignment-instruction
   #:special-variable-bind-instruction
   #:global-function-reference-instruction
   #:function-name
   #:progv-instruction
   #:variable-name
   #:enclose-instruction
   #:catch-instruction
   #:throw-instruction
   #:datum
   #:register
   #:name
   #:readers
   #:writers
   #:value
   #:single-value-register
   #:multiple-value-register
   #:literal))
